# configuration/production.yaml
application:
  host: 0.0.0.0
database:
  host: "postgres"
  # require_ssl: true
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "wnwoghd22@knu.ac.kr"